baseURL = "http://pubsofoldrus.com/"
languageCode = "en-us"
title = "Пабы старой Руси"
theme = "vanilla-bootstrap"

[taxonomies]
tag = "tags"

[[menu.nav]]
name = "Home"
pre = "home"
url = "/"
weight = 1

[[menu.nav]]
name = "Заметки"
pre = "edit"
url = "/posts/"
weight = 2

[[menu.nav]]
name = "Теги"
pre = "tags"
url = "/tags/"
weight = 3

[[menu.nav]]
name = "RSS"
pre = "rss"
url = "/index.xml"
weight = 4