baseURL = "https://www.pubsofoldrus.com"
languageCode = "ru"
title = "Пабы старой Руси"
theme = "fuji"

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    isPlainText = true
    notAlternative = true
    mediaType = "application/json"
    path = "/search/"

[params]
  author = "Kirill Taran"
  copyrightStartYear = "2020"
  enableTelegramWelcomeMessage = true

  googleAnalyticsTid = "G-SGMB7J7M24"
  yandexMetrikaId = 71173345

[taxonomies]
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "Главная"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "О сайте"
    url = "/about/"
    weight = 2
  [[menu.nav]]
    name = "Поиск"
    url = "/search/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4

  [[menu.link]]
    name = "Канал в Телеграме"
    url = "https://t.me/pubsofoldrus"